In [1]:
import pandas as pd
import numpy as np
import os
import re

# Load the dataset
folder = 'c:/Users/shubh/Desktop/Tableau_Project'
file_path = os.path.join(folder, 'Heart_new2 (1).csv')
df = pd.read_csv(file_path)

print('Initial Shape:', df.shape)
print('Missing values:', df.isnull().sum().sum())
print('Duplicates:', df.duplicated().sum())

# Display the first few rows
df.head()

Initial Shape: (4500, 18)
Missing values: 0
Duplicates: 6

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3,30,No,Female,55-59,White,Yes,Yes,Very good,5,Yes,No,Yes
1,No,20.34,No,No,Yes,0,0,No,Female,80 or older,White,No,Yes,Very good,7,No,No,No
2,No,26.58,Yes,No,No,20,30,No,Male,65-69,White,Yes,Yes,Fair,8,Yes,No,No
3,No,24.21,No,No,No,0,0,No,Female,75-79,White,No,No,Good,6,No,No,Yes
4,No,23.71,No,No,No,28,0,Yes,Female,40-44,White,No,Yes,Very good,8,No,No,No

In [2]:
def split_camel_case(s):
    if s == 'BMI': return 'BMI'
    return re.sub(r'(?<!^)(?=[A-Z])', ' ', s)

new_cols = {col: split_camel_case(col) for col in df.columns}
df.rename(columns=new_cols, inplace=True)

print('New Columns:', df.columns.tolist())

New Columns: ['Heart Disease', 'BMI', 'Smoking', 'Alcohol Drinking', 'Stroke', 'Physical Health', 'Mental Health', 'Diff Walking', 'Sex', 'Age Category', 'Race', 'Diabetic', 'Physical Activity', 'Gen Health', 'Sleep Time', 'Asthma', 'Kidney Disease', 'Skin Cancer']

In [3]:
def get_bmi_category(bmi):
    if bmi < 18.5: return 'Underweight'
    elif bmi < 25: return 'Normal Weight'
    elif bmi < 30: return 'Overweight'
    else: return 'Obese'

df['BMI Category'] = df['BMI'].apply(get_bmi_category)
df['BMI Category'].value_counts()

BMI Category
Obese            1753
Overweight       1531
Normal Weight    1151
Underweight        65
Name: count, dtype: int64

In [4]:
# Drop duplicates
df.drop_duplicates(inplace=True)

print('Final Shape:', df.shape)
df.head()

Final Shape: (4494, 19)

,Heart Disease,BMI,Smoking,Alcohol Drinking,Stroke,Physical Health,Mental Health,Diff Walking,Sex,Age Category,Race,Diabetic,Physical Activity,Gen Health,Sleep Time,Asthma,Kidney Disease,Skin Cancer,BMI Category
0,No,16.60,Yes,No,No,3,30,No,Female,55-59,White,Yes,Yes,Very good,5,Yes,No,Yes,Underweight
1,No,20.34,No,No,Yes,0,0,No,Female,80 or older,White,No,Yes,Very good,7,No,No,No,Normal Weight
2,No,26.58,Yes,No,No,20,30,No,Male,65-69,White,Yes,Yes,Fair,8,Yes,No,No,Overweight
3,No,24.21,No,No,No,0,0,No,Female,75-79,White,No,No,Good,6,No,No,Yes,Normal Weight
4,No,23.71,No,No,No,28,0,Yes,Female,40-44,White,No,Yes,Very good,8,No,No,No,Normal Weight

In [5]:
out_path = os.path.join(folder, 'Heart_Disease_Tableau_Ready.csv')
df.to_csv(out_path, index=False)
print('Saved prepared dataset to:', out_path)

Saved prepared dataset to: c:/Users/shubh/Desktop/Tableau_Project\Heart_Disease_Tableau_Ready.csv